model: /home/model/Qwen3.5-35B-A3B
trust_remote_code: true
model_class: llm

template: qwen3_5_nothink

kernel_config:
  name: auto
  include_kernels: auto

quant_config: null

init_config:
  name: init_on_meta

dist_config:
  name: fsdp_turbo
  dcp_path: null
  cp_size: 1

  ep_size: 16
  ep_fsdp_size: 1
  ep_dispatcher: eager
  param_dtype: bf16

  ep_modules:
    - model.language_model.layers.{*}.mlp.experts

  ep_fsdp_modules:
    - model.language_model.layers.{*}.mlp

train_dataset: data/v1_sft_demo.yaml

output_dir: outputs/perf_qwen35_a3b_fsdp_turbo_1000
micro_batch_size: 1
cutoff_len: 256
learning_rate: 1.0e-4
bf16: true
max_steps: 1000

### sample
sample_backend: hf
max_new_tokens: 128
